import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Space_Grotesk } from '@next/font/google'
import Footer from "./components/Footer";

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '700'], 
})

export const metadata: Metadata = {
  title: "Wendo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className} >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
